### PR TITLE
feat: add verbose flag, use it to toggle signal logging

### PR DESCRIPTION
**Pull request by zachequi**
This is actually my first time every writing in go, so please excuse/forgive any lack of best practices or other obvious oversights.

I tested this by building locally, running commands with and without `-v` and `--verbose`, seems to silence the signal logging as expected.

### CODE REVIEW

**Comment by zachequi** [comment]
@busser Apologies for the extra email noise, any chance I could get your thoughts on this?

**Comment by busser** [comment]
Hey @zachequi, sorry for the late response. For some reason I didn't get notified about your issue and your PR. I'll have to look into that later.

Regarding your feature request, I think it's a good idea. During my tests, logging signals wasn't very verbose but I can imagine how in some environments this could create a lot of noise. This raises the question of logging in murmur in general, which has been an afterthought up until now. I agree that we shouldn't log signals by default, and that having a flag that enables signal logging is a good idea.

I think the way you implemented the new flag is fine. Go-wise, it's good work! However I'm not certain that adding a `--verbose` flag is the right option. It forces us to have only two levels of logging: verbose and non-verbose. There is a lot of information we probably want to log when murmur runs, and all that information has varying levels of importance. I would much rather have the common four levels: debug, info, warning, and error. The default level could be info or warning (we can determine that later) and signals would only be logged if the log level is debug.

Since Go will be adding a structured logging package to the standard library very soon, I would rather wait for that and add full-featured logging to murmur then.

In the mean time, I suggest we simplify your PR massively: let's just remove the signal logging. The only reason it's there is because it makes the feature easier to test, and that's not a good reason to create noise in users' logs. That means that we don't need a flag for now. I'll open an issue regarding logging, so we can keep track of this discussion.

**Comment by busser** [comment]
Closed in favor of #378

**Comment by busser** [comment]
Thanks for your help on this @zachequi. Even though this PR hasn't been merged, murmur is now better because of you!

Release [v0.6.1](https://github.com/busser/murmur/releases/tag/v0.6.1) no longer logs signals 👍

**Comment by zachequi** [comment]
Thank you sir!  Appreciate your attention to this issue and work on whisper!

**Pull request closed without merging**
